task_manager/urls.py
from django.urls import path

from task_manager.views import (
    index,
    TaskListView,
    TaskCreateView,
    TaskDetailView,
    TaskUpdateView,
    TaskDeleteView,
    WorkerCreateView,
    WorkerDetailView,
    WorkerPositionUpdateView,
    WorkerDeleteView,
    toggle_complete_task,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
)

urlpatterns = [
    path("", index, name="index"),

    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/<int:pk>/update/",
         TaskUpdateView.as_view(),
         name="task-update"
         ),
    path("tasks/<int:pk>/delete/",
         TaskDeleteView.as_view(),
         name="task-delete"
         ),
    path("tasks/<int:pk>/toggle_complete/",
         toggle_complete_task,
         name="toggle-complete-task"
         ),

    path("worker/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"),
    path("worker/create/", WorkerCreateView.as_view(), name="worker-create"),
    path(
        "worker/<int:pk>/update/",
        WorkerPositionUpdateView.as_view(),
        name="worker-update",
    ),
    path(
        "worker/<int:pk>/delete/",
        WorkerDeleteView.as_view(),
        name="worker-delete",
    ),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/",
         TagUpdateView.as_view(),
         name="tag-update"
         ),
    path("tags/<int:pk>/delete/",
         TagDeleteView.as_view(),
         name="tag-delete"
         ),

]

app_name = "task_manager"

task_manager_settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("task_manager.urls", namespace="task_manager")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

task_manager/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class Worker(AbstractUser):
    position = models.ForeignKey(
        "Position",
        on_delete=models.CASCADE,
        null=True
    )

    class Meta:
        verbose_name = "worker"
        verbose_name_plural = "workers"

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("task_manager:worker-detail", kwargs={"pk": self.pk})


class Position(models.Model):
    name = models.CharField(max_length=63, unique=True)

    def __str__(self):
        return self.name


PRIORITY_CHOICES = (
    ("Urgent", "Urgent"),
    ("High", "High"),
    ("Medium", "Medium"),
    ("Low", "Low")
)


class Task(models.Model):
    name = models.CharField(max_length=63)
    description = models.TextField()
    uploaded = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True)
    is_completed = models.BooleanField(default=False)
    priority = models.CharField(max_length=6, choices=PRIORITY_CHOICES)
    task_type = models.ForeignKey("TaskType", on_delete=models.DO_NOTHING)
    assignees = models.ManyToManyField(Worker, related_name="tasks")
    tags = models.ManyToManyField("Tag", related_name="tasks")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("task_manager:task-detail", kwargs={"pk": self.pk})


class TaskType(models.Model):
    name = models.CharField(max_length=63)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=63)

    def __str__(self):
        return self.name

task_manager/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.forms import SelectDateWidget

from task_manager.models import Worker, Task, Tag


class TaskNameSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"}),
    )


class WorkerCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Worker
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "position",
        )


class WorkerPositionUpdateForm(forms.ModelForm):
    class Meta:
        model = Worker
        fields = ["position"]


class TaskForm(forms.ModelForm):
    assignees = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Task
        fields = [
            "name",
            "description",
            "deadline",
            "priority",
            "task_type",
            "assignees",
            "tags"]

    deadline = forms.DateTimeField(
        label='What is deadline?',
        widget=forms.SelectDateWidget
    )

task_manager/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect

from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic

from task_manager.forms import (
    TaskNameSearchForm,
    WorkerPositionUpdateForm,
    WorkerCreationForm,
    TaskForm
)
from task_manager.models import Task, Worker, Tag


def index(request):
    """View function for the home page of the site."""
    user = request.user
    queryset = Task.objects.filter(assignees=user.id)
    num_tasks = queryset.count()
    num_high_priority_tasks = queryset.filter(
        priority__in=("Urgent", "High")
    ).count()
    num_finished_tasks = queryset.filter(is_completed=True).count()

    context = {
        "num_tasks": num_tasks,
        "num_high_priority_tasks": num_high_priority_tasks,
        "num_finished_tasks": num_finished_tasks,
    }

    return render(request, "task_manager/index.html", context=context)


class TaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    context_object_name = "task_list"
    template_name = "task_manager/task_list.html"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = TaskNameSearchForm(initial={
            "name": name,
        })

        return context

    def get_queryset(self):
        user = self.request.user
        queryset = Task.objects.filter(assignees=user.id).prefetch_related(
            "assignees").select_related("task_type")
        form = TaskNameSearchForm(self.request.GET)

        order_by = self.request.GET.get("order_by")
        is_completed = self.request.GET.get("is_completed")
        priority = self.request.GET.get("priority")

        if form.is_valid():
            if order_by:
                return queryset.filter(
                    name__icontains=form.cleaned_data["name"]
                ).order_by(order_by)
            if is_completed:
                return queryset.filter(
                    name__icontains=form.cleaned_data["name"],
                    is_completed=is_completed
                )
            if priority:
                return queryset.filter(
                    name__icontains=form.cleaned_data["name"],
                    priority=priority
                )
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskForm


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("task_manager:task-list")


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("task_manager:task-list")


class WorkerCreateView(generic.CreateView):
    model = Worker
    form_class = WorkerCreationForm


class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Worker
    queryset = Worker.objects.prefetch_related("tasks")


class WorkerPositionUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Worker
    form_class = WorkerPositionUpdateForm
    success_url = reverse_lazy("task_manager:worker-detail")


class WorkerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Worker
    success_url = reverse_lazy("task_manager:task-list")


@login_required
def toggle_complete_task(request, pk):
    task = get_object_or_404(Task, pk=pk)

    if task.is_completed:
        task.is_completed = False
    else:
        task.is_completed = True

    task.save()

    return HttpResponseRedirect(
        reverse_lazy("task_manager:task-detail", args=[pk])
    )


class TagListView(LoginRequiredMixin, generic.ListView):
    model = Tag


class TagCreateView(LoginRequiredMixin, generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("task_manager:tag-list")


class TagUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("task_manager:tag-list")


class TagDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("task_manager:tag-list")

templates/task_manager/index.html
{% extends "base.html" %}

{% block content %}
  <h1>Task Manager</h1>
  <br>
  {% if user.is_authenticated %}
  <p>The Task Manager has the following record counts:</p>
  <ul>
    <li><strong>Number of tasks:</strong> {{ num_tasks }}</li>
    <li><strong>Urgent and high priority
      tasks:</strong> {{ num_high_priority_tasks }}</li>
    <li><strong>Number of finished tasks:</strong> {{ num_finished_tasks }}
    </li>
  </ul>
  {% else %}
    Please
    <a href="http://127.0.0.1:8001/accounts/login/?next=/">Login</a>
    or
    <a href="{% url 'task_manager:worker-create' %}">Sign Up</a>
  {% endif %}

{% endblock %}

templates/task_manager/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/task_manager/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/task_manager/tag_list.html
{% extends "base.html" %}
{% load query_transform %}
{% load crispy_forms_filters %}

{% block content %}
  <h1 style="text-align: center">
    Tags List
    <a href="{% url 'task_manager:tag-create' %}"
       class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>
  <br>

  {% if tag_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for tag in tag_list %}
        <tr>
          <td>{{ tag.id }}</td>
          <td>{{ tag.name }}</td>
          <td>
            <a href="{% url 'task_manager:tag-update' pk=tag.id %}">
              Update
            </a>
          </td>
          <td>
            <a style="color: red"
               href="{% url 'task_manager:tag-delete' pk=tag.id %}">
              Delete
            </a>
          </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
    <p>There are no tags.</p>
  {% endif %}
{% endblock %}

templates/task_manager/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/task_manager/task_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    {{ task.name }}
    <a href="{% url 'task_manager:task-delete' pk=task.id %}"
       class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'task_manager:task-update' pk=task.id %}"
       class="btn btn-primary link-to-page">
      Update
    </a>

    {% if task.is_completed %}
      <a href="{% url 'task_manager:toggle-complete-task' pk=task.id %}"
         class="btn btn-danger link-to-page">
        Incomplete
      </a>
    {% else %}
      <a href="{% url 'task_manager:toggle-complete-task' pk=task.id %}"
         class="btn btn-success link-to-page">
        Complete
      </a>
    {% endif %}
  </h1>

  <p><strong>Description:</strong> {{ task.description }}</p>
  <p><strong>Deadline:</strong> {{ task.deadline }}</p>
  <p><strong>Priority:</strong>
    {% if task.priority == 'Urgent' %}
      <span style="color: red; font-weight: bold;">{{ task.priority }}</span>
    {% elif task.priority == 'High' %}
      <span style="font-weight: bold;">{{ task.priority }}</span>
    {% else %}
      <span>{{ task.priority }}</span>
    {% endif %}
  </p>
  <p><strong>Type:</strong> {{ task.task_type }}</p>
  <p><strong>Is completed?</strong> {{ task.is_completed }}</p>
  <p><strong>Tags:</strong>
    {% for tag in  task.tags.all %}
      {{ tag }}
    {% endfor %}

  <div class="ml-3">
    <h4 style="text-align: center">Workers</h4>

    <table class="table">
      <tr>
        <th>Username</th>
        <th>Name</th>
        <th>Position</th>
        <th>Email</th>
      </tr>
      {% for worker in task.assignees.all %}
        <tr>
          <td>
            {{ worker.username }}
          </td>
          <td>
            {{ worker.first_name }} {{ worker.last_name }}
          </td>
          <td>
            {{ worker.position }}
          </td>
          <td>
            {{ worker.email }}
          </td>
        </tr>
      {% empty %}
        <p>No workers!</p>
      {% endfor %}
    </table>
  </div>
{% endblock %}

templates/task_manager/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/task_manager/task_list.html
{% extends "base.html" %}
{% load query_transform %}
{% load crispy_forms_filters %}

{% block content %}
  <h1 style="text-align: center">
    Tasks List
    <a href="{% url 'task_manager:task-create' %}"
       class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>
  <br>
  <form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
    <input class="btn btn-secondary" type="submit" value="🔎">&emsp;&emsp;
    <b>Completed:</b>&nbsp;
    <label>
      <input id="complete_yes" type="checkbox" name="complete_yes"
             value="complete_yes"
             onchange='window.location.href=
                 "?{% url_replace request 'is_completed' 'True' %}"'
          {% if request.GET.is_completed == 'True' %} checked {% endif %}>
    </label>Yes&nbsp;

    <label>
      <input type="checkbox" name="complete_no" value="complete_no"
             onchange='window.location.href=
                 "?{% url_replace request 'is_completed' 'False' %}"'
          {% if request.GET.is_completed == 'False' %} checked {% endif %}>
    </label>No&emsp;&emsp;
    <b>Priority:</b>&nbsp;
    <label>
      <input type=checkbox name="urgent" value="urgent"
             onchange='window.location.href=
                 "?{% url_replace request 'priority' 'Urgent' %}"'
          {% if request.GET.priority == 'Urgent' %} checked {% endif %}>
    </label>Urgent&nbsp;
    <label>
      <input type="checkbox" name="high" value="high"
             onchange='window.location.href=
                 "?{% url_replace request 'priority' 'High' %}"'
          {% if request.GET.priority == 'High' %} checked {% endif %}>
    </label>High&nbsp;
    <label>
      <input type="checkbox" name="medium" value="medium"
             onchange='window.location.href=
                 "?{% url_replace request 'priority' 'Medium' %}"'
          {% if request.GET.priority == 'Medium' %} checked {% endif %}>
    </label>Medium&nbsp;
    <label>
      <input type="checkbox" name="low" value="low"
             onchange='window.location.href=
                 "?{% url_replace request 'priority' 'Low' %}"'
          {% if request.GET.priority == 'Low' %} checked {% endif %}>
    </label>Low&emsp;&emsp;
    <a href="{% url 'task_manager:task-list' %}">Reset filters</a>
  </form>
  <br>

  {% if task_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th><a href="?{% url_replace request 'order_by' 'deadline' %}"
               style="text-decoration: none; color: black">Deadline</a></th>
        <th><a href="?{% url_replace request 'order_by' 'priority' %}"
               style="text-decoration: none; color: black">Priority</a></th>
        <th><a href="?{% url_replace request 'order_by' 'task_type' %}"
               style="text-decoration: none; color: black">Type</a></th>
        <th>Completed</th>
      </tr>

      {% for task in task_list %}
        <tr>
          <td>{{ task.id }}</td>
          <td><a href="{% url 'task_manager:task-detail' pk=task.id %}">
            {{ task.name }}</a></td>
          <td>{{ task.deadline }}</td>
          {% if task.priority == 'Urgent' %}
            <td style="color: red; font-weight: bold;">{{ task.priority }}</td>
          {% elif task.priority == 'High' %}
            <td style="font-weight: bold;">{{ task.priority }}</td>
          {% else %}
            <td>{{ task.priority }}</td>
          {% endif %}
          <td>{{ task.task_type }}</td>
          <td><label>
            <input type="checkbox" name="completed_radio"
                   onclick="return false;"
                {% if task.is_completed %} checked {% endif %}>
          </label></td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
    <p>There are no task.</p>
  {% endif %}
{% endblock %}

templates/task_manager/worker_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete worker?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/task_manager/worker_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Username: {{ worker.username }}
    <a href="{% url 'task_manager:worker-delete' pk=worker.id %}"
       class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'task_manager:worker-update' pk=worker.id %}"
       class="btn btn-secondary link-to-page">
      Update
    </a>
  </h1>

  <p><strong>First name:</strong> {{ worker.first_name }}</p>
  <p><strong>Last name:</strong> {{ worker.last_name }}</p>
  <p><strong>Position:</strong> {{ worker.position }}</p>
  <p><strong>Is staff:</strong> {{ worker.is_staff }}</p>

  <div class="ml-3">
    <h4 style="text-align: center">Tasks</h4>

    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Deadline</th>
        <th>Priority</th>
        <th>Type</th>
      </tr>
    {% for task in worker.tasks.all %}
      <tr>
      <td> {{ task.id }} </td>
      <td> {{ task.name }}</td>
      <td> {{ task.deadline }}</td>
      <td> {{ task.priority }}</td>
      <td> {{ task.task_type }}</td>
      {#        <p class="text-muted"><strong>Id:</strong> {{car.id}}</p>#}

    {% empty %}
      <p>No task!</p>
    {% endfor %}
  </div>
{% endblock %}

templates/task_manager/worker_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} worker</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}